"""Monitor codegen — emit a STANDALONE, dependency-free local monitor script.

Each generated `<Role>_monitor.py` embeds the role's projected EFSM (states,
transitions, accepting set) plus its refinement predicates, and walks a trace
against them. It is plain deterministic code — no LLM, no stjp_core import,
no network — so it can be dropped next to ANY agent runtime (a Claude skill
hook, a Foundry gate, a CI check) and give the same verdicts as
stjp_core/monitor/monitor.py for its role.

Use:
    python <Role>_monitor.py trace.jsonl          # verdict for the whole trace
    echo '{"sender":...}' | python <Role>_monitor.py -   # streaming, one/line

Exit code 0 = conformant, 1 = violation(s).

Research basis: Bocchi, Chen, Demangeon, Honda, Yoshida (FORTE'13 / TCS'17) —
local monitors synthesized from projected local types; global safety from
local enforcement.
"""
from __future__ import annotations

import json
from pathlib import Path

from stjp_core.compiler.efsm_parser import EFSM


_TEMPLATE = '''#!/usr/bin/env python3
"""Auto-generated STJP local monitor — role {role}, protocol {protocol}.

Deterministic code generated from the Scribble-validated projection.
Do not edit by hand; re-generate from the protocol instead.
Generated by stjp_core.generation.monitor_codegen.
"""
import ast, json, sys

ROLE = {role!r}
PROTOCOL = {protocol!r}
INITIAL = {initial!r}
ACCEPTING = {accepting!r}
# (source_state, direction, peer, label, payload_type, target_state)
TRANSITIONS = {transitions}
# {{(sender, receiver, label): (declared_type, [predicates over x])}}
REFINEMENTS = {refinements}

_SAFE = {{'len': len, 'abs': abs, 'min': min, 'max': max, 'int': int,
         'float': float, 'str': str, 'bool': bool, 'True': True,
         'False': False, 'None': None}}
_OK_NODES = (ast.Expression, ast.BoolOp, ast.BinOp, ast.UnaryOp, ast.Compare,
             ast.Call, ast.Constant, ast.Name, ast.Load, ast.IfExp, ast.Tuple,
             ast.List, ast.Attribute, ast.And, ast.Or, ast.Not, ast.Add,
             ast.Sub, ast.Mult, ast.Div, ast.FloorDiv, ast.Mod, ast.Pow,
             ast.UAdd, ast.USub, ast.Eq, ast.NotEq, ast.Lt, ast.LtE, ast.Gt,
             ast.GtE, ast.In, ast.NotIn, ast.Is, ast.IsNot)
_OK_ATTRS = {{'lower', 'upper', 'strip', 'startswith', 'endswith', 'replace'}}


def _safe_eval(pred, x):
    tree = ast.parse(pred, mode='eval')
    for node in ast.walk(tree):
        if isinstance(node, ast.Attribute):
            if node.attr not in _OK_ATTRS:
                raise ValueError('unsafe attribute: ' + node.attr)
        elif not isinstance(node, _OK_NODES):
            raise ValueError('unsafe node: ' + type(node).__name__)
    return eval(compile(tree, '<refn>', 'eval'), {{'x': x, '__builtins__': {{}}, **_SAFE}})


class LocalMonitor:
    """Walks the embedded EFSM. check() returns None or a violation dict."""

    def __init__(self):
        self.state = INITIAL
        self.violations = []

    def _expected(self):
        return [f"{{t[2]}}{{'!' if t[1] == 'send' else '?'}}{{t[3]}}"
                for t in TRANSITIONS if t[0] == self.state]

    def check(self, sender, receiver, label, payload=""):
        if sender == ROLE:
            direction, peer = 'send', receiver
        elif receiver == ROLE:
            direction, peer = 'receive', sender
        else:
            return None  # not this role's message
        idx = label.find('(')
        norm = label[:idx] if idx > 0 else label
        match = None
        for t in TRANSITIONS:
            if (t[0] == self.state and t[1] == direction
                    and t[2] == peer and t[3] == norm):
                match = t
                break
        if match is None:
            v = {{'role': ROLE, 'type': 'off_protocol', 'state': self.state,
                 'got': f"{{direction}} {{peer}} {{label}}",
                 'expected': self._expected()}}
            self.violations.append(v)
            return v
        refn = REFINEMENTS.get((sender, receiver, norm))
        if refn and payload:
            declared_type, preds = refn
            try:
                x = ({{'int': int, 'float': float}}.get(declared_type, str))(payload)
                if declared_type == 'bool':
                    x = str(payload).lower() in ('true', '1', 'yes')
            except (TypeError, ValueError):
                v = {{'role': ROLE, 'type': 'refinement_failed', 'state': self.state,
                     'got': payload, 'expected': [f'type {{declared_type}}']}}
                self.violations.append(v)
                return v
            for pred in preds:
                try:
                    ok = _safe_eval(pred, x)
                except Exception as e:
                    ok = False
                    pred = f"{{pred}} (error: {{e}})"
                if not ok:
                    v = {{'role': ROLE, 'type': 'refinement_failed',
                         'state': self.state, 'got': payload, 'expected': [pred]}}
                    self.violations.append(v)
                    return v
        self.state = match[5]
        return None

    def check_termination(self):
        if self.state not in ACCEPTING:
            v = {{'role': ROLE, 'type': 'premature_termination',
                 'state': self.state, 'got': 'end of trace',
                 'expected': self._expected()}}
            self.violations.append(v)
            return v
        return None


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    stream = sys.stdin if argv[1] == '-' else open(argv[1], encoding='utf-8')
    mon = LocalMonitor()
    n = 0
    for line in stream:
        line = line.strip()
        if not line:
            continue
        e = json.loads(line)
        n += 1
        v = mon.check(e.get('sender', ''), e.get('receiver', ''),
                      e.get('label', ''), str(e.get('payload', '')))
        if v:
            print(json.dumps({{'step': n, 'violation': v}}))
    mon.check_termination()
    verdict = {{'role': ROLE, 'protocol': PROTOCOL, 'events': n,
               'conformant': not mon.violations,
               'violations': mon.violations, 'final_state': mon.state}}
    print(json.dumps(verdict))
    return 0 if verdict['conformant'] else 1


if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
'''


def generate_monitor_script(efsm: EFSM, refinements: dict | None = None) -> str:
    """Render the standalone monitor script for one role's EFSM.

    `refinements` is the dict from refinement_checker.parse_refn_file —
    entries keyed (sender, receiver, label) are compiled in; choice guards
    (keyed ('__choice__', ...)) stay with the full SessionMonitor (they need
    cross-message value tracking the lean script deliberately omits)."""
    transitions = [(t.source, t.direction, t.peer, t.label, t.payload_type,
                    t.target) for t in efsm.transitions]
    refn_map = {}
    for key, r in (refinements or {}).items():
        if (isinstance(key, tuple) and len(key) == 3 and key[0] != "__choice__"
                and hasattr(r, "predicates")):
            sender, receiver, label = key
            if sender == efsm.role or receiver == efsm.role:
                refn_map[(sender, receiver, label)] = (
                    r.declared_type, list(r.predicates))

    return _TEMPLATE.format(
        role=efsm.role,
        protocol=efsm.protocol_name,
        initial=efsm.initial_state,
        accepting=set(efsm.accepting_states),
        transitions=repr(sorted(transitions)),
        refinements=repr(refn_map),
    )


def write_monitor_script(efsm: EFSM, out_dir: Path,
                         refinements: dict | None = None) -> Path:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{efsm.role}_monitor.py"
    path.write_text(generate_monitor_script(efsm, refinements), encoding="utf-8")
    return path
